language: cpp
compiler:
  - gcc
  - clang
brefore_install:
  - sudo apt-get update
  - sudo apt-get install libglew-dev libgl1-mesa-dev libglew-dev freeglut3-dev libassimp-dev libfreeimage-dev
script: cmake ./source && make