language: cpp
compiler:
  - gcc
  - clang
script: 
  - sudo apt-get update
  - sudo apt-get install libglew-dev libgl1-mesa-dev libglew-dev freeglut3-dev libassimp-dev libfreeimage-dev libassimp3 	
  - cmake ./source && make